Add shellcheck to pre-commit
I have limited the checks with --severity=error, as we have lots of code
that assumes (correctly) that variables don't contain spaces (for
example, source files in this repo or debian package names).

Change-Id: Ife5fe924c8394b6afaca26f7dfd793621b504259
GitOrigin-RevId: 2cca9e55625671c977b3c06eeb9242d7d62f4143

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -2,6 +2,8 @@
 # git hook to ensure code style
 # ln -sf ../../scripts/pre-commit .git/hooks/
 
+set -o pipefail
+
 result=0
 
 # Allow to call the pre-commit hook with a list of files. This allows to run the
@@ -67,7 +69,7 @@ for workspace_dir in $(find -name WORKSPACE -printf "%h\n"); do
   bzl="$workspace_dir/BUILD.bazel"
   if [ -e "$bzl" ] && grep -q "gazelle(" "$bzl"; then
     # This calls gazelle for every workspace, affected or not.
-    if [ -n "$go_files" -o -n "$build_files" ]; then
+    if [[ -n "$go_files" || -n "$build_files" ]]; then
       diff=$(cd ${workspace_dir} && bazel run :gazelle -- -mode=diff 2>/dev/null)
       if [ -n "$diff" ]; then
         echo "$diff"
@@ -141,11 +143,11 @@ tf_files=$(files_matching "\.tf$")
 # apps repo, which doesn't have a top-level bazel-out directory.
 TERRAFORM="$HOME/.cache/cloud-robotics/terraform"
 if [ -n "$tf_files" ]; then
-  tf_dirs=$(for f in "$tf_files"; do dirname $f; done | sort | uniq)
+  tf_dirs=$(dirname $tf_files | sort | uniq)
   for tf_dir in $tf_dirs; do
     if ! ${TERRAFORM} fmt -write=false -list=false -check=true $tf_dir; then
       ${TERRAFORM} fmt -write=false -list=false -diff=true $tf_dir
-      echo "To fix, run: ${TERRAFROM} fmt $tf_dir"
+      echo "To fix, run: ${TERRAFORM} fmt $tf_dir"
       result=1
     fi
   done
@@ -171,6 +173,24 @@ if [[ -n "$md_files" || -n "$example_files" ]]; then
       echo "To fix, run: $EMBEDMD -w \$(git ls-files | grep '\\.md$')"
       result=1
     fi
+  fi
+fi
+
+SHELLCHECK_DIR="$HOME/.cache/cloud-robotics"
+SHELLCHECK="${SHELLCHECK_DIR}/shellcheck-v0.6.0/shellcheck"
+sh_files=$(files_matching "(\.sh$|scripts/)")
+if [[ -n "$sh_files" ]] ; then
+  if [[ ! -e "$SHELLCHECK" ]] ; then
+    mkdir -p "$SHELLCHECK_DIR"
+    curl -fsSL https://storage.googleapis.com/shellcheck/shellcheck-v0.6.0.linux.x86_64.tar.xz \
+      | tar -C "$SHELLCHECK_DIR" -xJf - || exit 1
+  fi
+  # Note: using a lower severity than `error` results in many warnings about
+  # quoting in places where it would be lots of work to handle spaces correctly
+  # (eg scripts/pre-commit).
+  if ! "$SHELLCHECK" --severity=error --external-sources $sh_files ; then
+    echo "ERROR: shellcheck found issues. These need to be fixed manually." >&2
+    result=1
   fi
 fi
 
